# Generated by Django 4.0.6 on 2023-02-25 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField()),
                ('provincia', models.CharField(choices=[('CH', 'CHACO'), ('CR', 'CORRIENTES'), ('MS', 'MISIONES')], default='CH', max_length=3)),
                ('localidad', models.CharField(choices=[('RES', 'RESISTENCIA'), ('BAR', 'BARRANQUERAS'), ('FON', 'FONTANA')], default='RES', max_length=3)),
                ('direccion', models.CharField(choices=[('RES', 'RESISTENCIA'), ('BAR', 'BARRANQUERAS'), ('FON', 'FONTANA')], default='RES', max_length=150)),
                ('tel', models.CharField(choices=[('RES', 'RESISTENCIA'), ('BAR', 'BARRANQUERAS'), ('FON', 'FONTANA')], default='RES', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
