version: '3'

volumes:
  osneal_local_postgres_data: {}
  osneal_local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: osneal_local_django
    container_name: osneal_local_django
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: osneal_production_postgres
    container_name: osneal_local_postgres
    volumes:
      - osneal_local_postgres_data:/var/lib/postgresql/data
      - osneal_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - "5434:5432"


  redis:
    image: redis:6
    container_name: osneal_local_redis


