# Generated by Django 4.0.6 on 2023-02-25 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('raza', models.CharField(max_length=250, null=True)),
                ('pelaje', models.CharField(max_length=250, null=True)),
                ('edad', models.IntegerField(default=0, null=True)),
                ('num_microchip', models.IntegerField(default=0)),
                ('Descripción', models.TextField(max_length=5000, null=True)),
                ('Dueño', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, null=True)),
                ('tipo', models.CharField(max_length=150, null=True)),
                ('nombre_vacuna', models.CharField(max_length=150, null=True)),
                ('proxima_dosis', models.DateTimeField(null=True)),
                ('descripcion', models.TextField(max_length=5000, null=True)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascotas.mascota')),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_turno', models.DateTimeField()),
                ('descripcion', models.TextField(max_length=5000, null=True)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascotas.mascota')),
            ],
        ),
    ]
