# Generated by Django 4.0.6 on 2023-02-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mascota',
            old_name='Dueño',
            new_name='duenio',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='Descripción',
        ),
        migrations.RemoveField(
            model_name='vacuna',
            name='mascota',
        ),
        migrations.AddField(
            model_name='mascota',
            name='descripcion',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='vacuna',
            name='lote',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='vacuna',
            name='vacunas',
            field=models.ManyToManyField(to='mascotas.mascota'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='descripcion',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='vacuna',
            name='descripcion',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
