# Generated by Django 4.0.6 on 2023-02-25 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mascota',
            old_name='Dueño',
            new_name='duenio',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='Descripción',
        ),
        migrations.AddField(
            model_name='mascota',
            name='descripcion',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='descripcion',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='vacuna',
            name='descripcion',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
