# Generated by Django 4.0.6 on 2023-02-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0002_rename_dueño_mascota_duenio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacuna',
            name='mascota',
        ),
        migrations.AddField(
            model_name='mascota',
            name='vacunas',
            field=models.ManyToManyField(to='mascotas.vacuna'),
        ),
        migrations.AddField(
            model_name='vacuna',
            name='lote',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
