# Generated by Django 4.0.6 on 2023-02-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0003_remove_vacuna_mascota_mascota_vacunas_vacuna_lote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='vacunas',
        ),
        migrations.AddField(
            model_name='vacuna',
            name='vacunas',
            field=models.ManyToManyField(to='mascotas.mascota'),
        ),
    ]
