# Generated by Django 4.0.10 on 2023-03-22 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('micro_chip', models.CharField(max_length=250)),
                ('especie', models.CharField(max_length=250)),
                ('raza', models.CharField(max_length=250)),
                ('pelaje', models.ImageField(blank=True, null=True, upload_to='mascotas')),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('tipo_plan', models.CharField(choices=[('Plan Base', 'Plan Base'), ('Plan Estándar', 'Plan Estándar'), ('Plan Premium', 'Plan Premium')], default='Plan Base', max_length=250)),
                ('fecha_ingreso', models.DateField(auto_now_add=True, null=True)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
                ('fecha_baja', models.DateField(null=True)),
                ('activo', models.BooleanField(default=True)),
                ('duenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_vacuna', models.CharField(choices=[('Antirrábica', 'Antirrábica'), ('Puppy', 'Puppy'), ('Quintuple', 'Quintuple'), ('Sextuple', 'Sextuple'), ('Antitetánica', 'Antitetánica'), ('Mixomatosis', 'Mixomatosis')], max_length=250)),
                ('fecha_vacuna', models.DateField(null=True)),
                ('fecha_proxima_vacuna', models.DateField(null=True)),
                ('nro_vacuna', models.CharField(blank=True, max_length=250, null=True)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascotas.mascota')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_historial', models.DateField(null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascotas.mascota')),
            ],
        ),
    ]
