# Generated by Django 4.0.10 on 2023-03-23 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='micro_chip',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
