# Generated by Django 4.0.10 on 2023-03-31 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0002_mascota_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='pelaje',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
