# Generated by Django 4.0.10 on 2023-04-04 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0003_alter_mascota_pelaje'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historialclinico',
            old_name='descripcion',
            new_name='tratamiento',
        ),
        migrations.AddField(
            model_name='historialclinico',
            name='diagnostico',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
