# Generated by Django 4.0.10 on 2023-04-16 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0004_rename_descripcion_historialclinico_tratamiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='tipo_plan',
            field=models.CharField(choices=[('Plan Base', 'Plan Base'), ('Plan Estándar', 'Plan Estándar'), ('Plan Premium', 'Plan Premium')], max_length=250),
        ),
    ]
