# Generated by Django 4.0.10 on 2023-04-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0005_alter_mascota_tipo_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='mascotas/'),
        ),
    ]
