# Generated by Django 4.0.10 on 2023-04-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0006_mascota_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='fecha_baja',
            field=models.DateField(blank=True, default=None),
        ),
    ]
