# Generated by Django 4.0.10 on 2023-04-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0007_alter_mascota_fecha_baja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='fecha_baja',
            field=models.DateField(blank=True, default='1900-01-01'),
        ),
    ]
