# Generated by Django 4.0.10 on 2023-03-17 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de login')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.BigIntegerField()),
                ('telefono', models.BigIntegerField(null=True)),
                ('direccion', models.CharField(max_length=250)),
                ('localidad', models.CharField(max_length=150)),
                ('provincia', models.CharField(max_length=150)),
                ('codigo_postal', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('fecha_alta', models.DateField(auto_now_add=True)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('modificado', models.DateField(auto_now=True)),
                ('tipo_usuario', models.CharField(choices=[('propietario', 'Propietario'), ('veterinario', 'Veterinario'), ('administrador', 'Administrador')], max_length=100)),
                ('observaciones', models.TextField(blank=True, max_length=500, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
