# Generated by Django 4.0.10 on 2023-03-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='dni',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
