# Generated by Django 4.0.10 on 2023-03-04 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_propietario_modificado_veterinario_modificado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propietario',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='veterinario',
            name='estado',
        ),
    ]
