# Generated by Django 4.0.10 on 2023-03-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_propietario_estado_remove_veterinario_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propietario',
            name='codigo_postal',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='direccion',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='dni',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='localidad',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='observaciones',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='provincia',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='telefono',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='codigo_postal',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='direccion',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='dni',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='localidad',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='observaciones',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='provincia',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='telefono',
            field=models.BigIntegerField(),
        ),
    ]
