# Generated by Django 4.0.10 on 2023-05-27 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mascotas', '0008_alter_mascota_fecha_baja'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_corta', models.CharField(max_length=250)),
                ('descripcion', models.TextField()),
                ('tipo_turno', models.CharField(choices=[('Veterinaria', 'Veterinaria'), ('Peluquería', 'Peluquería')], max_length=250)),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascotas.mascota')),
            ],
        ),
    ]
